[project]
name = "data-processing-sample"
version = "0.1.0"
description = "Processes data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.5.3",
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "flower>=2.0.1",
    "jinja2>=3.1.6",
    "pillow>=11.2.1",
    "python-dotenv>=1.1.0",
    "python-multipart>=0.0.20",
    "redis>=6.2.0",
    "requests>=2.32.4",
    "supabase>=2.15.3",
    "uvicorn>=0.34.3",
]
